# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  schedule:
    - cron: 0 20 * * *

permissions:
  contents: read

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt
        uses: actions/checkout@v3

      - name: Update feeds
        run: |
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
           rm -f ./.config*
           touch ./.config
           cat >> .config <<EOF
        
           CONFIG_TARGET_mediatek=y
           CONFIG_TARGET_mediatek_filogic=y
           CONFIG_TARGET_MULTI_PROFILE=y
           CONFIG_TARGET_DEVICE_mediatek_filogic_DEVICE_cmcc_rax3000m=y
           CONFIG_TARGET_DEVICE_PACKAGES_mediatek_filogic_DEVICE_cmcc_rax3000m=""
           CONFIG_ALL_KMODS=y
           CONFIG_ALL_NONSHARED=y
           CONFIG_DEVEL=y
           CONFIG_TARGET_PER_DEVICE_ROOTFS=y
           CONFIG_AUTOREMOVE=y
           CONFIG_BPF_TOOLCHAIN_BUILD_LLVM=y
           # CONFIG_BPF_TOOLCHAIN_NONE is not set
           CONFIG_BUILDBOT=y
           CONFIG_COLLECT_KERNEL_DEBUG=y
           CONFIG_HAS_BPF_TOOLCHAIN=y
           CONFIG_IB=y
           CONFIG_IMAGEOPT=y
           CONFIG_JSON_CYCLONEDX_SBOM=y
           CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
           CONFIG_KERNEL_BUILD_USER="builder"
           # CONFIG_KERNEL_KALLSYMS is not set
           CONFIG_PACKAGE_cgi-io=y
           CONFIG_PACKAGE_libbpf=m
           CONFIG_PACKAGE_libelf=m
           CONFIG_PACKAGE_liblucihttp=y
           CONFIG_PACKAGE_liblucihttp-ucode=y
           CONFIG_PACKAGE_libpcap=m
           CONFIG_PACKAGE_libxdp=m
           CONFIG_PACKAGE_luci=y
           CONFIG_PACKAGE_luci-app-firewall=y
           CONFIG_PACKAGE_luci-app-opkg=y
           CONFIG_PACKAGE_luci-base=y
           CONFIG_PACKAGE_luci-light=y
           CONFIG_PACKAGE_luci-mod-admin-full=y
           CONFIG_PACKAGE_luci-mod-network=y
           CONFIG_PACKAGE_luci-mod-status=y
           CONFIG_PACKAGE_luci-mod-system=y
           CONFIG_PACKAGE_luci-proto-ipv6=y
           CONFIG_PACKAGE_luci-proto-ppp=y
           CONFIG_PACKAGE_luci-ssl=y
           CONFIG_PACKAGE_luci-theme-bootstrap=y
           CONFIG_PACKAGE_px5g-mbedtls=y
           CONFIG_PACKAGE_qosify=m
           CONFIG_PACKAGE_rpcd=y
           CONFIG_PACKAGE_rpcd-mod-file=y
           CONFIG_PACKAGE_rpcd-mod-iwinfo=y
           CONFIG_PACKAGE_rpcd-mod-luci=y
           CONFIG_PACKAGE_rpcd-mod-rrdns=y
           CONFIG_PACKAGE_rpcd-mod-ucode=y
           CONFIG_PACKAGE_tc-tiny=m
           CONFIG_PACKAGE_ucode-mod-html=y
           CONFIG_PACKAGE_ucode-mod-math=y
           CONFIG_PACKAGE_uhttpd=y
           CONFIG_PACKAGE_uhttpd-mod-ubus=y
           CONFIG_PACKAGE_xdp-filter=m
           CONFIG_PACKAGE_xdp-loader=m
           CONFIG_PACKAGE_xdpdump=m
           CONFIG_PACKAGE_zlib=m
           CONFIG_REPRODUCIBLE_DEBUG_INFO=y
           CONFIG_SDK=y
           CONFIG_SDK_LLVM_BPF=y
           CONFIG_TARGET_ALL_PROFILES=y
           CONFIG_USE_LLVM_BUILD=y
           CONFIG_VERSIONOPT=y
           CONFIG_VERSION_BUG_URL=""
           CONFIG_VERSION_CODE=""
           CONFIG_VERSION_DIST="OpenWrt"
           CONFIG_VERSION_FILENAMES=y
           CONFIG_VERSION_HOME_URL=""
           CONFIG_VERSION_HWREV=""
           CONFIG_VERSION_MANUFACTURER=""
           CONFIG_VERSION_MANUFACTURER_URL=""
           CONFIG_VERSION_NUMBER=""
           CONFIG_VERSION_PRODUCT=""
           CONFIG_VERSION_REPO="https://downloads.openwrt.org/releases/23.05.2"
           CONFIG_VERSION_SUPPORT_URL=""
           EOF
           sed -i 's/^[ \t]*//g' ./.config
           make defconfig

      - name: Download packages
        run: make download -j16

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
